steps:
  # Node.js 환경에서 Vue.js 앱 빌드
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Docker 이미지 빌드
  - name: 'docker:latest'
    image: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:$SHORT_SHA', '.']

  # Docker 이미지 Container Registry에 푸시
  - name: 'docker:latest'
    image: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:$SHORT_SHA']

  # latest 태그 추가 (선택 사항)
  - name: 'docker:latest'
    image: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:$SHORT_SHA', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:latest' ]
  - name: 'docker:latest'
    image: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:latest' ]

images: [ 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:$SHORT_SHA', 'asia.gcr.io/affable-heading-456202-r3/vue-nginx:latest' ]

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 900s