steps:
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar -czf dist.tar.gz -C dist .
        gsutil cp dist.tar.gz gs://vue-pension-builder-bucket/dist/dist.tar.gz