# 1. npm install        → node_modules
# 2. npm run build      → dist 생성
# 3. docker build       → dist 포함된 nginx 이미지 생성
# 4. docker push        → 커밋 해시 기반 이미지 푸시
# 5. tag latest & push  → 최신 버전도 유지

steps:
  # 1. Vue 설치
  - name: 'node:lts'
    args:
      - install
    entrypoint: npm

  # 2. 빌드
  - name: 'node:lts'
    args:
      - run
      - build
    entrypoint: npm

  # 3. Docker 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA', '.']

  # 4. 커밋 해시 버전 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA']

  # 5. latest 태그로 이미지 추가
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:latest']


  # 6. MIG 무중단 재시작 (최신 이미지 반영용)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "🔁 MIG 무중단 롤링 재시작 시작"
        gcloud compute instance-groups managed rolling-action restart instance-group-4 \
          --zone=asia-northeast3-a \
          --max-unavailable=1

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
