steps:
  # 1. Node 설치
  - name: 'node:lts'
    args:
      - install
    entrypoint: npm

  # 2. Code 빌드
  - name: 'node:lts'
    args:
      - run
      - build
    entrypoint: npm

  # 3. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA', '.']

  # 4. 커밋 해시 버전 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA']

  # 5. latest 태그로 이미지 추가
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:$SHORT_SHA', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/affable-heading-456202-r3/vm-docker/vue-nginx:latest']


  # 6. MIG 무중단 재시작 (최신 Docker 이미지 반영용)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud compute instance-groups managed rolling-action restart instance-group-4 \
          --zone=asia-northeast3-a \
          --max-unavailable=1

options:
  logging: CLOUD_LOGGING_ONLY
