steps:
  - name: 'node:lts'
    dir: 'directory-1/frontend'
    args: ['install']
    entrypoint: npm

  - name: 'node:lts'
    dir: 'directory-1/frontend'
    args: ['run', 'build:${_BUILD_ENV}']
    entrypoint: npm

  # 3. Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'directory-1/frontend'
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_DOCKER_IMAGE_URL}:$SHORT_SHA'
      - '--build-arg'
      - '.'

  # 4. 커밋 해시 버전 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_DOCKER_IMAGE_URL}:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY