steps:
  # 1. Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'directory-1/frontend'
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_DOCKER_IMAGE_URL}:$SHORT_SHA'
      - '--build-arg'
      - 'BUILD_ENV=${_BUILD_ENV}'
      - '.'

  # 2. 커밋 해시 버전 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_DOCKER_IMAGE_URL}:$SHORT_SHA'

  # 3. latest 태그로 이미지 추가
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - tag
      - '${_DOCKER_IMAGE_URL}:$SHORT_SHA'
      - '${_DOCKER_IMAGE_URL}:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_DOCKER_IMAGE_URL}:latest'

  # 4. MIG 무중단 재시작 (최신 Docker 이미지 반영용)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud compute instance-groups managed rolling-action start-update ${_MIG_NAME} \
          --version=template=${_TEMPLATE_NAME} \
          --zone=${_MIG_ZONE} \
          --max-unavailable=0 \
          --max-surge=1 \
          --minimal-action=replace \
          --region=${_MIG_REGION}

options:
  logging: CLOUD_LOGGING_ONLY
